In [5]:
from numpy import *
a = arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [7]:
print("a shape is  {0}".format(a.shape))
print("a ndim is  {0}".format(a.ndim))
print("a dytype name is {0}".format(a.dtype.name))
print("a itemsize is {0}".format(a.itemsize))
print("a site is {0}".format(a.size))

a shape is  (3, 5)
a ndim is  2
a dytype name is int64
a itemsize is 8
a site is 15


In [10]:
from numpy import array
a = array([2,3,4])
print type(a)
print "a type is:", a.dtype
b = array([1.2,3.5,4.1])
print b.dtype

<type 'numpy.ndarray'>
a type is: int64
float64


In [13]:
b = array( [ (1.5,2,3), (4,5,6) ] )
print b 

[[ 1.5  2.   3. ]
 [ 4.   5.   6. ]]


In [15]:
c = array( [ [1,2], [3,4] ], dtype=complex )
print c 

[[ 1.+0.j  2.+0.j]
 [ 3.+0.j  4.+0.j]]


In [17]:
zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [21]:
ones((2,3,4),dtype=int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [23]:
zeros((2,3,4))

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [25]:
arange(10,30,5)

array([10, 15, 20, 25])

In [27]:
arange(0,2,0.3)

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [30]:
b = arange(12).reshape(4,3)
print b 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [32]:
arange(24).reshape(2,3,4) #3d arry

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [34]:
a = array( [20,30,40,50] )
b = arange( 4 )
print b 
c = a-b
print c

[0 1 2 3]
[20 29 38 47]


In [35]:
b**2

array([0, 1, 4, 9])

In [37]:
10*sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [39]:
a < 35

array([ True,  True, False, False], dtype=bool)

In [43]:
A = array([[1,1],[0,1]])
B = array([[2,0],[3,4]])
A*B

array([[2, 0],
       [0, 4]])

In [44]:
dot(A,B)

array([[5, 4],
       [3, 4]])

In [47]:
a = ones((2,3), dtype=int)
print "a is before", a 
b = random.random((2,3))
print "b before is",b
a *= 3
print "a is after", a 
b += a 
print "b after is",b 


a is before [[1 1 1]
 [1 1 1]]
b before is [[ 0.17236847  0.03376411  0.97544162]
 [ 0.96685541  0.68419643  0.88698617]]
a is after [[3 3 3]
 [3 3 3]]
b after is [[ 3.17236847  3.03376411  3.97544162]
 [ 3.96685541  3.68419643  3.88698617]]


In [48]:
a = ones(3, dtype=int32)
print a 
b = linspace(0, pi, 3)
print b 
print b.dtype.name

[1 1 1]
[ 0.          1.57079633  3.14159265]
float64


In [51]:
c = a +b 
print c 
print c.dtype.name
d = exp(c*1j)
print d 
print d.dtype.name

[ 1.          2.57079633  4.14159265]
float64
[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]
complex128


In [55]:
a = random.random((2,3))
print a 
print a.sum()
print a.min()
print a.max()

[[ 0.87307455  0.63794528  0.99583099]
 [ 0.30899831  0.88768166  0.09129683]]
3.79482760958
0.0912968290122
0.995830992438


In [57]:
b = arange(12).reshape(3,4)
print b 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [59]:
print b.sum(axis=0)
print b.min(axis=1)
print b.cumsum(axis=1)

[12 15 18 21]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [61]:
B = arange(3)
print B 
print exp(B)
print sqrt(B)
C = array([2.,-1.,4.])
add(B,C)

[0 1 2]
[ 1.          2.71828183  7.3890561 ]
[ 0.          1.          1.41421356]


array([ 2.,  0.,  6.])

In [67]:
a = arange(10)**3
print a 
print a[2]
print a[2:5]
a[:6:2] = -1000
print a 
print a[::-1]
for i in a:
    print i**(1/3.)

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]
[-1000     1 -1000    27 -1000   125   216   343   512   729]
[  729   512   343   216   125 -1000    27 -1000     1 -1000]
nan
1.0
nan
3.0
nan
5.0
6.0
7.0
8.0
9.0


/Users/dushibing/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:9: RuntimeWarning: invalid value encountered in power


In [72]:
def f(x,y):
    return 10*x+y
b = fromfunction(f,(5,4),dtype=int)
print "b",b 
print "b[2,3]",b[2,3]
print "b[0:5,1]",b[0:5,1]
print "b[::,1]",b[::,1]
print "b[1:3,:]",b[1:3,:]

b [[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
b[2,3] 23
b[0:5,1] [ 1 11 21 31 41]
b[::,1] [ 1 11 21 31 41]
b[1:3,:] [[10 11 12 13]
 [20 21 22 23]]


In [76]:
for row in b:
    print row 

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [78]:
for element in b.flat:
    print element,

0 1 2 3 10 11 12 13 20 21 22 23 30 31 32 33 40 41 42 43


In [81]:
a = floor(10*random.random((3,4)))
print a 

[[ 0.  1.  8.  3.]
 [ 1.  5.  2.  6.]
 [ 0.  0.  9.  0.]]


In [83]:
a.ravel()

array([ 0.,  1.,  8.,  3.,  1.,  5.,  2.,  6.,  0.,  0.,  9.,  0.])

In [84]:
a.shape = (6,2)
print a 
a.transpose()

[[ 0.  1.]
 [ 8.  3.]
 [ 1.  5.]
 [ 2.  6.]
 [ 0.  0.]
 [ 9.  0.]]


array([[ 0.,  8.,  1.,  2.,  0.,  9.],
       [ 1.,  3.,  5.,  6.,  0.,  0.]])